before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/passwork
    #id: passwork
    binary: passwork
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.AppVersion={{.Version}}
archives:
  - files:
      - "autocomplete/*"
    # format: binary
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
brews:
  - tap:
      owner: Sebor
      name: homebrew-tap

    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"

    folder: Formula

    homepage: "https://github.com/Sebor/passwork-cli"
    description: "Command Line Interface tool for https://passwork.me/"
    license: "MIT"

    install: |
      bin.install "passwork"
      prefix.install "README.md"
      bash_completion.install "autocomplete/bash_autocomplete" => "passwork"
